#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Composer
picom &
# Network
#nm-applet &
# Keyboard Layout
setxkbmap es &
# Wallpaper
#feh --bg-scale Escritorio/Wallpapers/casa-noche-azul.jpg &
# Window Manager
qtile
#Bloq Num
numlockx on
#Wallpaper gif
back4.sh 0.010 /home/miguel/Escritorio/Wallpapers/Japo_Luvia.gif &